### PR TITLE
deveops/dev-container

### PR DESCRIPTION
**Pull request by snguyen1**
Hi y'all,

This has 3 services:
- Semaphore scheduler
- Semaphore api
- Semaphore db (Postgres)

This PR includes:
- VS Code Launcher so help you start the project easily (Docker Desktop required): 
image
- Docker files and `docker-compose.yml` file
- Updated .gitignore file
- Updated README.md file
- Rename `.env.dict` to `.env.dist`
- Default connection string using postgresql in `.env.dist`
- Add a `init_db.py` script to initialize the database

WIP: Postgres database container refuses connection from inside another container (this is due to hostname resolving issue)

### CODE REVIEW

**Comment by bestrada33** [comment]
I am getting this error when trying to run compose dev up:
image

I already had created the venv, so it exists in that location.

**Comment by snguyen1** [comment]
> I am getting this error when trying to run compose dev up: image
> 
> I already had created the venv, so it exists in that location.



> I am getting this error when trying to run compose dev up: image
> 
> I already had created the venv, so it exists in that location.

Thanks for testing! I've made an update. Please test again when you have time.
You may want to run `docker-compose -f docker-compose.dev.yml down` and `docker-compose -f docker-compose.dev.yml build`

**Comment by snguyen1** [comment]
Added Rabbitmq service
image

**Review by bestrada33 — CHANGES_REQUESTED** [review]
`importlib` in `requirements.txt` is causing problems as it apparently comes with later versions of python already so trying to install it gives an error. It is not needed in this project and should be removed. (It is removed in main already.)

**Comment by snguyen1** [comment]
> `importlib` in `requirements.txt` is causing problems as it apparently comes with later versions of python already so trying to install it gives an error. It is not needed in this project and should be removed. (It is removed in main already.)

I just merged with `main`. Should get the latest `requirements.txt` file

**Comment by bestrada33** [comment]
For whatever reason Docker installs a really old version of SQLALCHEMY
image

Requesting to now specify version number 2.0.17 in requirements.txt:
image

**Comment by snguyen1** [comment]
> For whatever reason Docker installs a really old version of SQLALCHEMY image
> 
> Requesting to now specify version number 2.0.17 in requirements.txt: image

@bestrada33 

> For whatever reason Docker installs a really old version of SQLALCHEMY image
> 
> Requesting to now specify version number 2.0.17 in requirements.txt: image

I added the version for sqlalchemy! Please `docker image rm -f semaphore-semaphore-dev-main` to remove the dev image and rebuild it to get the latest change

**Comment by matdenkas** [comment]
## Meeting notes 11/22/2023
- DB container starting 
- API container start
- Scheduler container is getting shut off before it can make the db, but you can run it again and its fine
- When attempting to test Semaphore, tests fail because there are no FK rows in the REF table. 
- Meeting again on Friday to debug

**Comment by snguyen1** [comment]
`docker-compose build` && `docker-compose up`
looks like everything is running without crashing!

**Pull request merged**
