### PR TITLE
60 research api tech and develop plan to implamnet

### PR DESCRIPTION
**Pull request by bestrada33**

### CODE REVIEW

**Review by matdenkas — APPROVED** [review]
Looks amazing to me!

**Review by matdenkas — CHANGES_REQUESTED** [review]
Can we change the name of main.py to something more descriptive?

**Comment by bestrada33** [comment]
> Can we change the name of main.py to something more descriptive?

What do you have in mind? From what I've seen, it's not a strict requirement, but most FastAPI apps call this file main.py or app.py

**Review by matdenkas — APPROVED** [review]

**Comment by lovelysandlonelys** [comment]
worked with matthew, importlib had issues being installed from later versions of python, i removed it here and main removed it from main this will keep it from causing a merge error or being added back.

**Review by lovelysandlonelys — APPROVED** [review]
looks good!

**Pull request merged**
