### PR TITLE
moving tests into folders

### PR DESCRIPTION
**Pull request by lovelysandlonelys**
exactly what it says on the tin! i think that we really only have one test that could be considered a 'unit test' since all the other tests either use the database or call on other modules.

### CODE REVIEW

**Review by abeasley1722 — APPROVED** [review]
Improves the team's organization, so looks good to me.

**Review by matdenkas — CHANGES_REQUESTED** [review]
You need to update imports, failed to compile tests for me!

**Review by abeasley1722 — COMMENTED** [review]
Ignore my last comment. Tests did not work.

**Comment by bestrada33** [comment]
> You need to update imports, failed to compile tests for me!

Agreed

**Comment by lovelysandlonelys** [comment]
should compile correctly now!
image

**Review by bestrada33 — APPROVED** [review]
LGTM. All tests passed!

**Review by matdenkas — APPROVED** [review]

**Review by abeasley1722 — COMMENTED** [review]
LGTM. All tests ran for me.

**Review by abeasley1722 — APPROVED** [review]

**Comment by lovelysandlonelys** [comment]
image

To Do: 
add markers and try and fix the error message that NDFD is giving

**Comment by lovelysandlonelys** [comment]
ingesting classes now skipped when running tests folder
image

**Comment by lovelysandlonelys** [comment]
Dear Matthew, I'm unsure what exactly we would need to change about how the NDFD test reports a failure.

**Review by matdenkas — COMMENTED** [review]
Very nicely done. At some point we should standerdize the imports but this works.  We dont have enough time, tests passing so lets go ahead and merge

**Comment by lovelysandlonelys** [comment]
tests all run now but fail due to... i'm assuming... import problems
image

**Pull request closed without merging**
